import { createFileRoute, Link } from "@tanstack/react-router";

import { SiteShell } from "@/components/site-shell";
import { Button } from "@/components/ui/button";
import { WEAK_EVIDENCE_MESSAGE } from "@/lib/rag";

export const Route = createFileRoute("/about")({
  head: () => ({
    meta: [
      { title: "Methodology & Limits — Bhajan Marg Wisdom AI" },
      {
        name: "description",
        content:
          "How this source-grounded system works, what it refuses to do, and why it does not represent or impersonate Pujya Shri Hit Premanand Govind Sharan Ji Maharaj.",
      },
      { property: "og:title", content: "Methodology & Limits — Bhajan Marg Wisdom AI" },
      {
        property: "og:description",
        content:
          "Retrieval-first RAG, explicit answer modes, no invented quotes, and no claim of official affiliation.",
      },
    ],
  }),
  component: AboutPage,
});

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-2xl font-semibold text-foreground">{title}</h2>
      <div className="mt-3 space-y-3 text-[15px] leading-relaxed text-muted-foreground">
        {children}
      </div>
    </section>
  );
}

function AboutPage() {
  return (
    <SiteShell>
      <div className="mx-auto w-full max-w-3xl px-4 py-10 sm:py-14">
        <h1 className="font-display text-3xl font-semibold text-foreground">
          Methodology &amp; limits
        </h1>
        <p className="mt-3 text-[15px] leading-relaxed text-muted-foreground">
          Bhajan Marg Wisdom AI is an independent study aid for exploring publicly available
          teachings. Its entire trust model is source-grounded retrieval: nothing should be believed
          here that you cannot verify in the original recording or article.
        </p>

        <div className="mt-6 rounded-xl border border-destructive/30 bg-destructive/8 p-5 text-sm leading-relaxed text-foreground">
          <p className="font-semibold">What this is not</p>
          <ul className="mt-3 list-disc space-y-2 pl-5">
            <li>
              It does <strong>not</strong> represent, speak for, or impersonate Pujya Shri Hit
              Premanand Govind Sharan Ji Maharaj, and it does not clone his personality or voice.
            </li>
            <li>
              It is <strong>not</strong> official and claims no affiliation or endorsement from
              Shri Hit Radha Keli Kunj or Bhajan Marg unless such authorisation is publicly granted.
            </li>
            <li>
              It does <strong>not</strong> issue personal instructions, diksha, predictions, or
              rulings, and it is not a replacement for a living guru or for professional care.
            </li>
          </ul>
        </div>

        <Section title="How an answer is produced">
          <ol className="list-decimal space-y-2 pl-5">
            <li>Your question is language-detected (Hindi, Hinglish, English) and normalised.</li>
            <li>
              Retrieval runs first over indexed transcript segments; the top candidates are reranked
              and their citations validated against stored text and timestamps.
            </li>
            <li>
              Only then is an answer composed, strictly bounded to the retrieved segments. Every
              answer carries one of three modes: <strong>Direct teaching</strong> (short verbatim
              excerpt), <strong>Synthesized from teachings</strong> (AI-generated synthesis based on
              cited teachings), or <strong>Insufficient source evidence</strong>.
            </li>
            <li>Each answer is logged to an audit record with its citations and safety flags.</li>
          </ol>
        </Section>

        <Section title="Refusal over invention">
          <p>
            If retrieval is weak, the system refuses rather than paraphrasing something Maharaj Ji
            never said. In that case you will see:
          </p>
          <blockquote className="rounded-lg border-l-2 border-gold bg-muted/60 px-4 py-3 font-deva text-foreground">
            {WEAK_EVIDENCE_MESSAGE}
          </blockquote>
          <p>
            Quotations and timestamps are never generated by a model — they are copied from stored
            segments, and a citation that fails validation is dropped rather than shown.
          </p>
        </Section>

        <Section title="Sensitive questions">
          <p>
            For medical, mental-health, legal, financial, self-harm or crisis questions, sourced
            spiritual material is offered only as supplementary context alongside a clear prompt to
            seek qualified professional or emergency help. In an emergency, contact local emergency
            services; in India you can also reach Tele-MANAS at 14416.
          </p>
        </Section>

        <Section title="Copyright and takedown">
          <p>
            Sources are registered with explicit usage notes and permission state. Media is never
            re-hosted; we store metadata, short excerpts and deep links back to the original. Rights
            holders may request removal of any excerpt, and unauthorised material stays out of the
            index by default — which is why most sources currently show “metadata only”.
          </p>
        </Section>

        <Section title="Verify at the source">
          <p>
            Please treat every answer as a pointer, not an authority. Open the original satsang,
            listen in full context, and follow the guidance of your own guru and tradition.
          </p>
        </Section>

        <div className="mt-10 flex flex-wrap gap-3">
          <Button asChild>
            <Link to="/sources">See the source registry</Link>
          </Button>
          <Button asChild variant="outline">
            <Link to="/admin">Ingestion status</Link>
          </Button>
        </div>
      </div>
    </SiteShell>
  );
}
